version: '3'
services:
  dicecloud:
    container_name: dicecloud
    image: captainbowtie/dicecloud:1.0
    ports:
      - '8333:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
  mongo:
    container_name: dicecloud_database
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./dicecloud/data/db:/data/db
